// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVtGdj9oJUefZZ4D0sSNqy-gElI1pE8DQ',
    appId: '1:110376165079:web:b81ec94b3129f56c305a92',
    messagingSenderId: '110376165079',
    projectId: 'dukan-7071b',
    authDomain: 'dukan-7071b.firebaseapp.com',
    storageBucket: 'dukan-7071b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuG3Oh2Dv9EQei1UGm59NFpljN3zs4CnU',
    appId: '1:110376165079:android:835b4ffb105719ad305a92',
    messagingSenderId: '110376165079',
    projectId: 'dukan-7071b',
    storageBucket: 'dukan-7071b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3NsiKGfg7Hh5fduQZsaYO01hB84qPpA',
    appId: '1:110376165079:ios:1eebb0d57a62b452305a92',
    messagingSenderId: '110376165079',
    projectId: 'dukan-7071b',
    storageBucket: 'dukan-7071b.appspot.com',
    androidClientId: '110376165079-2nv6938v5ad1aki07qlffckiniap2uot.apps.googleusercontent.com',
    iosClientId: '110376165079-14sm7j0iu1t3r8un3gj5e1csmj445bet.apps.googleusercontent.com',
    iosBundleId: 'com.example.dukanVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3NsiKGfg7Hh5fduQZsaYO01hB84qPpA',
    appId: '1:110376165079:ios:09de3143d6a2e292305a92',
    messagingSenderId: '110376165079',
    projectId: 'dukan-7071b',
    storageBucket: 'dukan-7071b.appspot.com',
    androidClientId: '110376165079-2nv6938v5ad1aki07qlffckiniap2uot.apps.googleusercontent.com',
    iosClientId: '110376165079-jq0grsmggqk0fhht6ir1qnedm4e5i7pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dukanVendorApp.RunnerTests',
  );
}
